# Generated by Django 2.1.3 on 2018-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181202_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Ghost', max_length=40, verbose_name='Author'),
        ),
    ]
