# Generated by Django 2.1.3 on 2018-12-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_unlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlikes',
        ),
    ]
